"use strict";

kindFramework
    .constant('GLOBAL',{
        currentMenu : 'auto'
    })
    .constant('MAP_SERVER',{
        ip : 'http://127.0.0.1:3303'
    })
    .constant('CAMERA_LIST', [
    {"id" : "cam001", "name" : "CAM1", "cameraUrl": "192.168.123.233", "user" : "admin", "password":"init123~", "imageUrl" : "images/test.jpg", "eventCount" : 10},
    {"id" : "cam002", "name" : "CAM2", "cameraUrl": "192.168.123.208", "user" : "admin", "password":"init123~", "imageUrl" : "images/test.jpg", "eventCount" : 0},
    {"id" : "cam003", "name" : "CAM3", "cameraUrl": "192.168.123.233", "user" : "admin", "password":"init123~", "imageUrl" : "images/test.jpg", "eventCount" : 30},
    {"id" : "cam004", "name" : "CAM4", "cameraUrl": "192.168.123.208", "user" : "admin", "password":"init123~", "imageUrl" : "images/test.jpg", "eventCount" : 55}
    ])
    .constant('EVENT_LIST', [
        {"cameraId" : "cam001", "datas" : [
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
        ]},
        {"cameraId" : "cam003", "datas" : [
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
        ]},
        {"cameraId" : "cam002", "datas" : [
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"}
        ]},
        {"cameraId" : "cam003", "datas" : [
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
            {"time":"Now", "Event":"Motion"},
        ]},
        {"cameraId" : "cam004", "datas" : [
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"},
            {"Event":"Motion", "time":"Now"}
        ]},
    ])